sudo: false
language: java
addons:
  sonarqube:
    token:
      secure: UrWlItV1hI3bWE33RO0wwUyr5/1EDUOvdyDqwy/WkAJp/oaTsHMYsaP3RLW8y2dARup2SkP1xZ6lCMz43KpC2TEvdqS07Bd9z7G9WAB1bqAd9c3BUI8N/s8/N25Uv1a+zc8aiCNpq1u7uMsqwp2iZuibWnnCA7y+yyr1eWi3k5Y=
jdk:
  - oraclejdk8
script:
  - mvn install sonar:sonar
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"